# Generated by Django 2.2.24 on 2023-07-04 12:13

from django.db import migrations


def set_property_new_building(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
	    migrations.RunPython(set_property_new_building),
    ]
