# Generated by Django 3.1 on 2023-07-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_flat_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owners_phonenumber',
            new_name='owner_pure_phone',
        ),
    ]
