# Generated by Django 3.1 on 2023-07-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20230705_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(db_index=True, verbose_name='Наличие балкона'),
        ),
    ]
