# Generated by Django 3.1 on 2023-07-05 12:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230705_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owners_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Номер нормализированный владельца'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('owner_pure_phone', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('owners_phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Номер нормализированный владельца')),
                ('owner_flat', models.ManyToManyField(blank=True, help_text='Квартиры в собственности', related_name='user_flats', to='property.Flat')),
            ],
        ),
    ]
