# Generated by Django 3.1 on 2023-07-05 14:37

from django.db import migrations
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist


def del_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()
    print('Delete done.')

def add_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    try:
        if flats.exists():
            for flat in flats.iterator():
                owner_id = Owner.objects.get_or_create(owner=flat.owner, owner_pure_phone=flat.owner_pure_phone, owners_phonenumber=flat.owners_phonenumber)[0]
                owner_id.owner_flat.add(Flat.objects.get(id=flat.id))
    except Flat.DoesNotExist:
        print("Flat does not exist")



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230705_1627'),
    ]

    operations = [
         migrations.RunPython(del_owners),
         migrations.RunPython(add_owners),
    ]
