# Generated by Django 2.2.24 on 2023-07-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20230712_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сomplaint',
            old_name='complaint_flat',
            new_name='complaint',
        ),
    ]
