# Generated by Django 2.2.24 on 2023-07-12 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20230712_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owners_phonenumber',
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Номер владельца (нормализированный)'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='лайк'),
        ),
        migrations.AlterField(
            model_name='сomplaint',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_complaint', to='property.Flat', verbose_name='жалоба на квартиру'),
        ),
        migrations.AlterField(
            model_name='сomplaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaining_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь подавший жалобу'),
        ),
    ]
