# Generated by Django 2.2.24 on 2023-07-13 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20230713_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сomplaint',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='property.Flat', verbose_name='жалоба на квартиру'),
        ),
        migrations.AlterField(
            model_name='сomplaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaining', to=settings.AUTH_USER_MODEL, verbose_name='пользователь подавший жалобу'),
        ),
    ]
